version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - unconvert
    - unparam
    - gosec
    - errorlint
    - nilerr
    - exhaustive
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - whyNoLint
    exhaustive:
      default-signifies-exhaustive: true

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
